name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '31 17 * * *'

jobs:
  works-on-latest-v-and-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install colordiff libssl-dev libpcre3 libpcre3-dev

      - name: Checkout V
        uses: actions/checkout@v4
        with:
          repository: vlang/v

      - name: Build V
        run: make && ./v symlink -githubci

      - name: Checkout V AoC repo
        uses: actions/checkout@v2
        with:
          path: aoc

      - name: Install dependencies
        run: v install pcre

      - name: Run verify.v
        run: cd aoc && v run verify.v

      - name: Format
        run: v fmt . -c
